spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: ez-eureka-server
      password: senhansaber

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

